CREATE TABLE users (
	name VARCHAR(40) NOT NULL,
	email VARCHAR(50) primary KEY,
	city VARCHAR(20) NOT NULL,
	country VARCHAR(20) NOT NULL,
	password VARCHAR(64) NOT NULL,
	description TEXT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);